language: java

jdk:
- oraclejdk8

after_success:
- .buildscript/deploy_snapshot.sh

env:
  global:
  - secure: n+bE8vwlT7kLn+F/EsNGlgdrC46gENQadK2Tsujj9Pxoc3TWTTu/cfwV425+/mV3/xjYuTKcK6dxp9/+RnsjqhcmdWS04mgh4/5oWdyFxpchFyAiV/bm0e2TVxqunA45FuYdyGC83y7jpXbfrOLLGdLxOAGFO6fw4W2XwYlZWL+BpiiV1F2KuxUZjzIjNCL8oqvOQ+8Cc9o+SlDgyPE/61/Xeti8KHnlJlfRdZLaQ5ZliJzNt0EGci0Hvkb0gIwUZKJkml7Hb8pNhworh7JFAAQ7Q4vy73j8rmDyzAPQtHAlo+hrDV1lUbi2Eh0+EQiWCrotJnYaS/HEQveR/KdeAd9zGUmAJeSgCxMuLrTH+Q6wHhqEvFt4L9BfUXz4fWMHPSMNi3UhitD+celoLl/aus28eDhWlUCx73xJlwGkCpKS64r5f1Rhxl1eTrA/HZ6EZSapVY1u3jlTIlz2aH55Ei2/iSlNutcuQ1Jab8qmrgcOxW5XWE8BwwawU8NJBWW7ZgYcfVCmyvcSuwg1OkYCgRjZpjEu2QqTe+CsrMe+il2kZBwo1e1zmAU8xOOlhH8h2iemTKM7zRMWMKg1o4FV/bdD+M4+hBPG9z+4Zc1nGlTJLWpv5NWB1l0C0mgpN1tHDDuPeVhx0l0c4I846hiiRUMIoSNxC9qJULjkoNDlwek=
  - secure: tRBBIiQGQzTJP9qPS1DljGndnCp1K9xkVLAaswjfWpV+9BXSYWzW5TVIMS/UgGsqeKlpiBeJLlAQEGxXJGQofOcbVmm88gP8w0VPTWFUWlfrcwi0YoETomcZfK88ni9K8RYZwsQ6zuUn/ia/oxfj41Ki+tepzhpY7TvS4CogyffrCsBP+ciO9u0a3vaNC/ADOsG6h6i/4LpRPJEEnQO49iV5v7RrjOakSwbycjzk+Y2jUjHxynbCbKjfbGfkZTRKPnooM2Zn22MXJlY17s5pfHNlanhMGzmG1HhVygfFimuP3drSqERjqlwzcWabR7aFnM1iovtCnIAAKSrMyL2WidwwvaJtITb05jYcs9+GfNqWsQGWEFYWune2juaQ6NzI5o1mOox4V/593JQSmUgVNcjPhZbNEVIr2BG7klPAbKBOaevLfc/CHrQtNEJX5tIc5DZdW2oIHm70zQhFWF0u6xQfnjPxPsAPHIaVd6PN7R3CJJHqOgiC8AqFkK8zu2AQ2MhWPWc4/xwQEmmrYUgtHY0sn/xyUCAsPF6zD5/8y38sT1YGvCJOwWzzlkTwfBTNC+L3OqzqRUwHvH9v4aEYWUv29i2CaBucZ73lB/AhKRxCt4NSitJyhxyShb4k0ER+6gcJYk4Kg8DVX9HKhxUPP97kDyWmK9R0XXIw8gYHnd4=

notifications:
  email: false

sudo: false

cache:
  directories:
  - "$HOME/.m2"
